name: Build container

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aqualog-frontend
  SERVICE_NAME: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Read VERSION file
        id: getversion
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "pyproject.toml"
          field: "project.version"

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |   
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ghcr.io/${{ github.repository}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Lookup the Droplet IP address from the DigitalOcean API
        id: droplet_ip
        run: |
          DIGITALOCEAN_TOKEN="${{ secrets.DIGITALOCEAN_TOKEN }}"
          RESULT=$(curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/droplets?page=1&per_page=1")
          IP_ADDRESS=$(echo $RESULT | jq -r '.droplets[0].networks.v4[0].ip_address')
          echo "Droplet IP address: $IP_ADDRESS"
          echo "DROPLET_IP=$IP_ADDRESS" >> $GITHUB_ENV
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Reload DigitalOcean Droplet
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ env.DROPLET_IP }} "/opt/aqualog/service-restart.sh ${{ env.SERVICE_NAME }}"
